[project]
name = "python-capstone"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "John Parks", email = "johnwparks03@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "chromadb>=1.5.9",
    "langchain-google-genai>=4.4.0",
    "langchain-text-splitters>=1.1.2",
    "python-dotenv>=1.2.3",
    "rich>=15.0.0",
]

[project.scripts]
python-capstone = "python_capstone:main"

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
